// ─── SIGNATURE ───────────────────────────────────────────────────────────────
const SIGNATURE = [
  { kr:'카카오 벨벳', en:'Cacao Velvet', price:'₩25,000', desc:'부드러운 크림과 달콤한 카카오의 조화, 코코넛 워터가 깔끔하게 마무리해주는 디저트 스타일 칵테일', alc:'Alc. 18–20%', tags:['달콤한','부드러운','칵테일','중간'] },
  { kr:'망고 오! 망고', en:'Mango OH! Mango', price:'₩20,000', desc:'망고를 베이스로 상큼함과 청량감을 더한 하이볼', alc:'Alc. 8–10%', tags:['상큼한','과일향','탄산있는','가볍게','칵테일'] },
  { kr:'베리 요거트', en:'Berry Yogurt', price:'₩19,000', desc:'복분자의 진한 풍미에 요거트의 부드러움을 더한 새콤달콤한 디저트 스타일 칵테일', alc:'Alc. 8–10%', tags:['달콤한','상큼한','과일향','부드러운','가볍게','칵테일'] },
];

// ─── COCKTAILS ────────────────────────────────────────────────────────────────
const COCKTAILS = {
  'GIN': [
    { kr:'진 피즈', en:'Gin Fizz', price:'₩18,000', desc:'상큼한 레몬과 진, 톡 쏘는 탄산이 어우러진 클래식한 청량 칵테일', alc:'Alc. 12–16%', tags:['상큼한','탄산있는','가볍게','칵테일'] },
    { kr:'진 토닉', en:'Gin Tonic', price:'₩15,000', desc:'진의 향긋함과 토닉워터의 쌉쌀함이 완벽한 조화를 이루는 시그니처 하이볼', alc:'Alc. 10–15%', tags:['쌉쌀한','탄산있는','가볍게','칵테일','입문자'] },
    { kr:'진 리키', en:'Gin Rickey', price:'₩16,000', desc:'설탕 없이 깔끔하게, 라임과 탄산이 진의 풍미를 돋우는 드라이한 칵테일', alc:'Alc. 10–15%', tags:['상큼한','탄산있는','가볍게','칵테일'] },
    { kr:'김렛', en:'Gimlet', price:'₩18,000', desc:'진과 라임이 빚어낸 단순하지만 우아한, 단맛과 산미의 균형이 매력적인 칵테일', alc:'Alc. 20–25%', tags:['달콤한','상큼한','중간','칵테일'] },
    { kr:'드라이 마티니', en:'Dry Martini', price:'₩20,000', desc:'진과 드라이 베르무트가 만드는 가장 간결하고 도회적인 클래식', alc:'Alc. 30–35%', tags:['쌉쌀한','강렬한','강하게','칵테일'] },
    { kr:'네그로니', en:'Negroni', price:'₩20,000', desc:'진, 캄파리, 스위트 베르무트가 어우러진 쌉쌀한 매력의 이탈리안 클래식', alc:'Alc. 24–28%', tags:['쌉쌀한','강렬한','중간','칵테일'] },
  ],
  'VODKA': [
    { kr:'롱 티', en:'Long Island Iced Tea', price:'₩18,000', desc:'칵테일 계의 폭탄주, 이름과 달리 강렬한 한 잔', alc:'Alc. 20–22%', tags:['강렬한','중간','칵테일'] },
    { kr:'우스케 뮬', en:'Uisce Mule', price:'₩18,000', desc:'진저비어의 풍미와 시트러스 향을 느낄 수 있는 위스키가 어우러진 시원한 칵테일', alc:'Alc. 11–15%', tags:['상큼한','탄산있는','가볍게','칵테일','입문자'] },
    { kr:'블랙 러시안', en:'Black Russian', price:'₩20,000', desc:'보드카와 커피 리큐르가 만든, 묵직하고 부드러운 단맛의 칵테일', alc:'Alc. 20–25%', tags:['달콤한','쌉쌀한','중간','칵테일'] },
    { kr:'에스프레소 마티니', en:'Espresso Martini', price:'₩20,000', desc:'보드카와 에스프레소, 커피 리큐르의 조화로 완성된 깔끔하고 진한 커피 칵테일', alc:'Alc. 20–25%', tags:['쌉쌀한','중간','칵테일'] },
  ],
  'RUM': [
    { kr:'다이키리', en:'Daiquiri', price:'₩22,000', desc:'럼과 라임, 설탕이 빚어낸 클래식한 산뜻함. 단순함 속의 균형', alc:'Alc. 20–25%', tags:['상큼한','중간','칵테일'] },
    { kr:'모히또', en:'Mojito', price:'₩18,000', desc:'민트와 라임, 럼이 어우러진 청량한 여름의 한 잔', alc:'Alc. 10–15%', tags:['상큼한','탄산있는','가볍게','칵테일','입문자'] },
    { kr:'럼 올드패션', en:'Rum Old Fashioned', price:'₩25,000', desc:'럼의 깊은 풍미에 설탕과 비터스가 어우러진, 부드럽고 묵직한 클래식', alc:'Alc. 30–35%', tags:['달콤한','부드러운','강렬한','강하게','칵테일'] },
  ],
  'CALVADOS': [
    { kr:'칼바도스 진 리키', en:'Calvados Gin Rickey', price:'₩19,000', desc:'칼바도스와 진, 라임, 탄산이 어우러져 사과 향이 은은하게 퍼지는 드라이한 리키', alc:'Alc. 10–15%', tags:['상큼한','과일향','탄산있는','가볍게','칵테일'] },
    { kr:'칼바도스 진 피즈', en:'Calvados Gin Fizz', price:'₩21,000', desc:'청사과의 상쾌함을 담은 칼바도스와 진, 레몬, 탄산이 만난 부드러운 피즈', alc:'Alc. 12–18%', tags:['상큼한','과일향','탄산있는','가볍게','칵테일'] },
    { kr:'칼바도스 김렛', en:'Calvados Gimlet', price:'₩22,000', desc:'칼바도스의 과실 향과 라임의 산미가 진과 어우러져 과일 풍미가 살아나는 김렛', alc:'Alc. 20–25%', tags:['달콤한','상큼한','과일향','중간','칵테일'] },
    { kr:'노르망디', en:'Normandy', price:'₩24,000', desc:'칼바도스와 드라이 베르무트, 오렌지 비터스가 어우러진, 우아한 사과향 클래식', alc:'Alc. 18–20%', tags:['달콤한','과일향','중간','칵테일'] },
    { kr:'허니문', en:'Honeymoon', price:'₩25,000', desc:'허브의 은은한 달콤함과 상큼한 산미가 어우러진 부드럽고 균형 잡힌 클래식 칵테일', alc:'Alc. 18–22%', tags:['달콤한','부드러운','중간','칵테일'] },
    { kr:'칼바도스 소닉', en:'Calvados Sonic', price:'₩22,000', desc:'가볍고 청량한 탄산감에 은은한 과일 향이 더해진 산뜻한 하이볼 스타일', alc:'Alc. 10–14%', tags:['상큼한','과일향','탄산있는','가볍게','칵테일'] },
  ],
  'WHISKEY': [
    { kr:'위스키 하이볼', en:'Whiskey Highball', price:'₩18,000', desc:'위스키와 탄산수로만 완성되는 칵테일', alc:'', tags:['탄산있는','부드러운','가볍게','칵테일','입문자'] },
    { kr:'위스키 사워', en:'Whiskey Sour', price:'₩22,000', desc:'버번과 레몬, 설탕이 어우러진 새콤달콤한 위스키 입문자용 클래식', alc:'Alc. 15–20%', tags:['달콤한','상큼한','중간','칵테일','입문자'] },
    { kr:'아마레또 사워', en:'Amaretto Sour', price:'₩22,000', desc:'아몬드 향의 달콤함과 레몬의 상큼함이 어우러진 부드러운 사워 칵테일', alc:'Alc. 20%', tags:['달콤한','상큼한','중간','칵테일','입문자'] },
    { kr:'올드 패션', en:'Old Fashioned', price:'₩22,000', desc:'설탕과 비터스, 위스키만으로 완성되는 가장 단순하고 가장 묵직한 한 잔', alc:'Alc. 30–35%', tags:['달콤한','강렬한','강하게','칵테일'] },
    { kr:'갓파더', en:'GodFather', price:'₩22,000', desc:'스카치와 아마레또가 만나 강렬함 속에 은근한 단맛을 더한 매혹적인 칵테일', alc:'Alc. 25–30%', tags:['달콤한','강렬한','강하게','칵테일'] },
    { kr:'맨하탄', en:'Manhattan', price:'₩24,000', desc:'라이 위스키와 스위트 베르무트, 비터스가 어우러진 우아하고 절제된 클래식', alc:'Alc. 28%', tags:['달콤한','강렬한','강하게','칵테일'] },
    { kr:'리볼버', en:'Revolver', price:'₩22,000', desc:'버번과 커피 리큐르, 오렌지 비터가 어우러진 스모키한 향의 위스키 마티니', alc:'Alc. 30–35%', tags:['쌉쌀한','강렬한','강하게','칵테일'] },
    { kr:'사제락', en:'Sazerac', price:'₩23,000', desc:'페이쇼 비터와 압샌트의 아로마가 위스키에 스며든, 뉴올리언스 스타일의 헤리티지 칵테일', alc:'Alc. 35%', tags:['강렬한','강하게','칵테일'] },
    { kr:'하이랜드 쿨러', en:'Highland Cooler', price:'₩20,000', desc:'스카치의 풍미에 생강과 레몬이 더해진 상쾌한 위스키 하이볼', alc:'Alc. 10–15%', tags:['상큼한','탄산있는','가볍게','칵테일'] },
    { kr:'페니실린', en:'Penicillin', price:'₩22,000', desc:'스모키한 위스키와 생강, 꿀, 레몬이 어우러진 따뜻하면서도 강렬한 한 잔', alc:'Alc. 20–25%', tags:['스모키','달콤한','상큼한','중간','칵테일'] },
    { kr:'초크 앤 스모크', en:'Choke and Smoke', price:'₩22,000', desc:'탈리스커 기주의 클래식한 칵테일', alc:'Alc. 40%', tags:['스모키','강렬한','강하게','칵테일'] },
  ],
  'LIQUER': [
    { kr:'카카오 피즈', en:'Cacao Fizz', price:'₩18,000', desc:'카카오의 달콤 쌉쌀함과 탄산의 청량함이 어우러진 디저트 같은 칵테일', alc:'Alc. 6%', tags:['달콤한','쌉쌀한','탄산있는','가볍게','칵테일','입문자'] },
    { kr:'에프리콧 피즈', en:'Apricot Fizz', price:'₩19,000', desc:'살구 리큐르의 은은한 단맛과 산뜻한 거품이 어우러지는 상큼한 한 잔', alc:'Alc. 10–15%', tags:['달콤한','상큼한','과일향','탄산있는','가볍게','칵테일'] },
    { kr:'엘더플라워 피즈', en:'Elderflower Fizz', price:'₩21,000', desc:'꽃향 가득한 엘더플라워와 탄산이 어우러진, 은은하고 청량한 한 잔', alc:'Alc. 10–15%', tags:['달콤한','과일향','탄산있는','가볍게','칵테일'] },
  ],
  'BRANDY': [
    { kr:'사이드카', en:'SideCar', price:'₩25,000', desc:'브랜디, 트리플 섹, 레몬 주스의 조화로 탄생한 달콤쌉싸름한 황금빛 한 잔', alc:'Alc. 22–30%', tags:['달콤한','상큼한','중간','칵테일'] },
    { kr:'프렌치 커넥션', en:'French Connection', price:'₩25,000', desc:'코냑과 아마레또가 어우러진 달콤하고 부드러운 클래식 칵테일', alc:'Alc. 30–34%', tags:['달콤한','부드러운','강하게','칵테일'] },
    { kr:'어텀 리브스', en:'Autumn Leaves', price:'₩24,000', desc:'허브의 깊은 달콤함에 은은한 스파이스와 부드러운 버번의 따뜻함이 느껴지는 칵테일', alc:'Alc. 28–32%', tags:['달콤한','부드러운','강하게','칵테일'] },
    { kr:'피스코 사워', en:'Pisco Sour', price:'₩22,000', desc:'부드러운 거품과 함께 상큼한 산미와 은은한 단맛이 조화로운 클래식 칵테일', alc:'Alc. 18–22%', tags:['상큼한','달콤한','부드러운','중간','칵테일'] },
  ],
  'APEROL': [
    { kr:'아페롤 피즈', en:'Aperol Fizz', price:'₩21,000', desc:'가볍고 부드러운 탄산감에 은은한 시트러스 향이 더해진 산뜻하고 청량한 한 잔', alc:'Alc. 10–15%', tags:['상큼한','쌉쌀한','탄산있는','가볍게','칵테일','입문자'] },
    { kr:'아페롤 토닉', en:'Aperol Tonic', price:'₩21,000', desc:'쌉쌀함과 상큼한 향이 어우러진, 가볍게 즐기기 좋은 청량한 하이볼 스타일', alc:'Alc. 10–15%', tags:['쌉쌀한','탄산있는','가볍게','칵테일','입문자'] },
    { kr:'아페롤 네그로니', en:'Aperol Negroni', price:'₩25,000', desc:'쌉쌀함과 오렌지 계열의 향이 부드럽게 이어지는 밸런스 좋은 네그로니', alc:'Alc. 20–25%', tags:['쌉쌀한','과일향','중간','칵테일'] },
  ],
  'COFFEE': [
    { kr:'사케라또', en:'Shakerato', price:'₩8,000', desc:'에스프레소를 차갑게 흔들어낸, 진한 커피 향과 시원한 쌉쌀함이 매력적인 이탈리안 아이스 커피. 위스키와 페어링을 추천합니다.', alc:'', tags:['쌉쌀한','가볍게'] },
  ],
};

// ─── WHISKEY ─────────────────────────────────────────────────────────────────
const WHISKEY = {
  'SPEYSIDE': [
    { kr:'글렌피딕 12Y', en:'Glenfiddich 12Y', g30:16, g60:29, tags:['달콤한','과일향','부드러운','위스키','입문자'] },
    { kr:'글렌피딕 15Y', en:'Glenfiddich 15Y', g30:27, g60:49, tags:['달콤한','과일향','부드러운','위스키'] },
    { kr:'글렌피딕 16Y 에스터 마틴', en:'Glenfiddich 16Y', g30:29, g60:57, tags:['달콤한','과일향','위스키'] },
    { kr:'글렌피딕 18Y', en:'Glenfiddich 18Y', g30:41, g60:74, tags:['달콤한','과일향','부드러운','위스키'] },
    { kr:'글렌알라키 10Y CS', en:'Glen Allachie 10Y Batch 10 CS', g30:30, g60:57, tags:['달콤한','강렬한','위스키'] },
    { kr:'글렌알라키 10Y 모스카텔', en:'Glen Allachie 10Y Moscatel', g30:30, g60:54, tags:['달콤한','과일향','위스키'] },
    { kr:'글렌알라키 11Y', en:'Glen Allachie 11Y', g30:37, g60:67, tags:['달콤한','위스키'] },
    { kr:'글렌알라키 12Y', en:'Glen Allachie 12Y', g30:23, g60:42, tags:['달콤한','부드러운','위스키','입문자'] },
    { kr:'글렌알라키 15Y', en:'Glen Allachie 15Y', g30:35, g60:63, tags:['달콤한','위스키'] },
    { kr:'글렌알라키 18Y', en:'Glen Allachie 18Y', g30:50, g60:90, tags:['달콤한','강렬한','위스키'] },
    { kr:'미클토어 더 오리지널', en:'Meikle Toir The Original', g30:23, g60:41, tags:['스모키','위스키'] },
    { kr:'미클토어 더 셰리 원', en:'Meikle Toir The Sherry One', g30:25, g60:45, tags:['달콤한','스모키','위스키'] },
    { kr:'미클토어 터보', en:'Meikle Toir The Turbo', g30:25, g60:45, tags:['스모키','강렬한','위스키'] },
    { kr:'맥네어스 럼릭 12Y', en:"MacNair's Lum Reek 12Y", g30:20, g60:36, tags:['스모키','달콤한','위스키'] },
    { kr:'맥네어스 럼릭 10Y CS', en:"MacNair's Lum Reek 10Y CS", g30:28, g60:51, tags:['스모키','강렬한','위스키'] },
    { kr:'더 글렌리벳 12Y', en:'The Glenlivet 12Y', g30:16, g60:29, tags:['달콤한','과일향','부드러운','위스키','입문자'] },
    { kr:'더 글렌리벳 15Y', en:'The Glenlivet 15Y', g30:25, g60:45, tags:['달콤한','과일향','위스키'] },
    { kr:'더 글렌리벳 18Y', en:'The Glenlivet 18Y', g30:42, g60:76, tags:['달콤한','과일향','부드러운','위스키'] },
    { kr:'탐듀 12Y', en:'Tamdhu 12Y', g30:18, g60:32, tags:['달콤한','위스키','입문자'] },
    { kr:'탐듀 15Y', en:'Tamdhu 15Y', g30:33, g60:59, tags:['달콤한','위스키'] },
    { kr:'탐듀 18Y', en:'Tamdhu 18Y', g30:50, g60:90, tags:['달콤한','강렬한','위스키'] },
    { kr:'맥캘란 12Y 더블 오크 캐스크', en:'Macallan 12Y Double Oak Cask', g30:20, g60:36, tags:['달콤한','부드러운','위스키','입문자'] },
    { kr:'맥캘란 12Y 셰리 오크 캐스크', en:'Macallan 12Y Sherry Oak Cask', g30:27, g60:49, tags:['달콤한','과일향','위스키'] },
    { kr:'맥캘란 15Y 더블캐스크', en:'Macallan 15Y Double Cask', g30:35, g60:62, tags:['달콤한','부드러운','위스키'] },
    { kr:'맥캘란 18Y 셰리 오크 캐스크', en:'Macallan 18Y Sherry Oak Cask', g30:55, g60:99, tags:['달콤한','강렬한','위스키'] },
    { kr:'발베니 12Y 싱글 배럴', en:'Balvenie 12Y Single Barrel', g30:25, g60:45, tags:['달콤한','과일향','위스키'] },
    { kr:'발베니 12Y 더블우드', en:'Balvenie 12Y Double Wood', g30:19, g60:35, tags:['달콤한','부드러운','위스키','입문자'] },
    { kr:'발베니 12Y 아메리칸 오크', en:'Balvenie 12Y American Oak', g30:25, g60:45, tags:['달콤한','위스키'] },
    { kr:'발베니 14Y 캐리비안 캐스크', en:'Balvenie 14Y Caribbean Cask', g30:33, g60:60, tags:['달콤한','과일향','위스키'] },
    { kr:'발베니 16Y 프렌치오크', en:'Balvenie 16Y French Oak', g30:42, g60:76, tags:['달콤한','과일향','위스키'] },
    { kr:'벤로막 10Y', en:'Benromach 10Y', g30:16, g60:29, tags:['달콤한','스모키','위스키','입문자'] },
    { kr:'벤로막 15Y', en:'Benromach 15Y', g30:33, g60:59, tags:['달콤한','스모키','위스키'] },
    { kr:'아벨라위 12Y', en:'Aberlour 12Y', g30:21, g60:38, tags:['달콤한','과일향','위스키'] },
    { kr:'아벨라위 아부나흐', en:"Aberlour A'bunadh", g30:32, g60:58, tags:['달콤한','강렬한','위스키'] },
  ],
  'HIGHLAND': [
    { kr:'글렌모렌지 오리지널', en:'Glenmorangie The Original', g30:19, g60:35, tags:['달콤한','과일향','부드러운','위스키','입문자'] },
    { kr:'글렌모렌지 라산타', en:'Glenmorangie Lasanta', g30:28, g60:50, tags:['달콤한','과일향','위스키'] },
    { kr:'글렌모렌지 더 넥타', en:'Glenmorangie The Nectar', g30:25, g60:45, tags:['달콤한','과일향','위스키'] },
    { kr:'글렌모렌지 퀸타 루반', en:'Glenmorangie Quinta Ruban', g30:25, g60:45, tags:['달콤한','과일향','위스키'] },
    { kr:'글렌모렌지 시그넷', en:'Glenmorangie Signet', g30:45, g60:81, tags:['달콤한','강렬한','위스키'] },
    { kr:'글렌드로낙 12Y', en:'Glendronach 12Y', g30:18, g60:32, tags:['달콤한','과일향','위스키','입문자'] },
    { kr:'글렌드로낙 15Y', en:'Glendronach 15Y', g30:33, g60:59, tags:['달콤한','강렬한','위스키'] },
    { kr:'글렌드로낙 18Y', en:'Glendronach 18Y', g30:45, g60:81, tags:['달콤한','강렬한','위스키'] },
    { kr:'글렌파클라스 15Y', en:'Glenfarclas 15Y', g30:33, g60:59, tags:['달콤한','위스키'] },
    { kr:'글렌파클라스 105 CS', en:'Glenfarclas 105 CS', g30:28, g60:50, tags:['달콤한','강렬한','위스키'] },
    { kr:'달모어 12Y', en:'Dalmore 12Y', g30:21, g60:38, tags:['달콤한','과일향','위스키','입문자'] },
    { kr:'달모어 12Y 셰리', en:'Dalmore 12Y Sherry', g30:31, g60:56, tags:['달콤한','과일향','위스키'] },
    { kr:'달모어 15Y', en:'Dalmore 15Y', g30:38, g60:69, tags:['달콤한','강렬한','위스키'] },
    { kr:'글렌 고인 12Y', en:'Glengoyne 12Y', g30:15, g60:27, tags:['달콤한','부드러운','위스키','입문자'] },
    { kr:'글렌 고인 15Y', en:'Glengoyne 15Y', g30:27, g60:49, tags:['달콤한','위스키'] },
    { kr:'글렌 고인 21Y', en:'Glengoyne 21Y', g30:55, g60:null, tags:['달콤한','강렬한','위스키'] },
    { kr:'달위니 15Y', en:'Dalwhinnie 15Y', g30:23, g60:41, tags:['달콤한','부드러운','위스키','입문자'] },
    { kr:'오반 14Y', en:'Oban 14Y', g30:25, g60:45, tags:['달콤한','스모키','위스키'] },
    { kr:'글렌 터렛 10Y 피트 스모크드', en:'GlenTurret 10Y Peat Smoked', g30:18, g60:32, tags:['스모키','위스키'] },
    { kr:'글렌 터렛 12Y', en:'GlenTurret 12Y', g30:25, g60:45, tags:['달콤한','위스키'] },
    { kr:'에드라두어 발레친 10Y', en:'Ballechin 10Y', g30:28, g60:50, tags:['스모키','강렬한','위스키'] },
    { kr:'에드라두어 2015 싱글 캐스크', en:'Edradour 2015 Single Cask', g30:35, g60:62, tags:['달콤한','위스키'] },
    { kr:'에드라두어 11Y 스몰 배치', en:'Edradour 11Y Small Batch', g30:30, g60:54, tags:['달콤한','위스키'] },
  ],
  'ISLAY': [
    { kr:'아드벡 10Y', en:'Ardbeg 10Y', g30:19, g60:35, tags:['스모키','강렬한','위스키'] },
    { kr:'아드벡 우가달', en:'Ardbeg Uigeadail', g30:28, g60:50, tags:['스모키','달콤한','강렬한','위스키'] },
    { kr:'아드벡 언 오', en:'Ardbeg An Oa', g30:25, g60:45, tags:['스모키','달콤한','위스키'] },
    { kr:'아드벡 코리브레칸', en:'Ardbeg Corryvreckan', g30:33, g60:60, tags:['스모키','강렬한','위스키'] },
    { kr:'아드벡 위비스티', en:'Ardbeg Wee Beastie', g30:18, g60:32, tags:['스모키','강렬한','위스키'] },
    { kr:'아드벡 19Y 트라이 반 배치6', en:'Ardbeg Traigh Bhan Batch 6', g30:40, g60:72, tags:['스모키','강렬한','위스키'] },
    { kr:'라가불린 11Y', en:'Lagavulin 11Y', g30:20, g60:36, tags:['스모키','강렬한','위스키'] },
    { kr:'라가불린 16Y', en:'Lagavulin 16Y', g30:32, g60:58, tags:['스모키','강렬한','위스키'] },
    { kr:'라프로익 10Y', en:'Laphroaig 10Y', g30:16, g60:29, tags:['스모키','강렬한','위스키'] },
    { kr:'라프로익 셀렉트', en:'Laphroaig Select', g30:16, g60:29, tags:['스모키','위스키'] },
    { kr:'라프로익 쿼터캐스크', en:'Laphroaig Quarter Cask', g30:22, g60:40, tags:['스모키','달콤한','강렬한','위스키'] },
    { kr:'보모어 12Y', en:'Bowmore 12Y', g30:16, g60:29, tags:['스모키','달콤한','위스키','입문자'] },
    { kr:'보모어 18Y', en:'Bowmore 18Y', g30:35, g60:63, tags:['스모키','달콤한','위스키'] },
    { kr:'라세이', en:'Raasay', g30:18, g60:32, tags:['스모키','위스키'] },
    { kr:'킬 호만 사닉', en:'Kilchoman Sanaig', g30:23, g60:41, tags:['스모키','강렬한','위스키'] },
    { kr:'옥토모어 15.3', en:'Octomore 15.3', g30:85, g60:null, tags:['스모키','강렬한','위스키'] },
    { kr:'옥토모어 16.3', en:'Octomore 16.3', g30:90, g60:null, tags:['스모키','강렬한','위스키'] },
  ],
  'ISLAND': [
    { kr:'탈리스커 10Y', en:'Talisker 10Y', g30:16, g60:29, tags:['스모키','강렬한','위스키'] },
    { kr:'탈리스커 10Y Old Bottle', en:'Talisker 10Y Old Bottle', g30:22, g60:null, tags:['스모키','강렬한','위스키'] },
    { kr:'탈리스커 25Y', en:'Talisker 25Y', g30:90, g60:162, tags:['스모키','강렬한','위스키'] },
    { kr:'하이랜드파크 12Y', en:'Highland Park 12Y', g30:18, g60:32, tags:['달콤한','스모키','위스키','입문자'] },
    { kr:'하이랜드파크 18Y', en:'Highland Park 18Y', g30:38, g60:68, tags:['달콤한','스모키','위스키'] },
    { kr:'라그 배치 1', en:'LAGG Batch 1', g30:35, g60:63, tags:['스모키','달콤한','위스키'] },
    { kr:'라그 배치 2', en:'LAGG Batch 2', g30:35, g60:63, tags:['스모키','달콤한','위스키'] },
    { kr:'라그 배치 3', en:'LAGG Batch 3', g30:35, g60:63, tags:['스모키','달콤한','위스키'] },
    { kr:'아란 10Y', en:'Arran 10Y', g30:18, g60:32, tags:['달콤한','과일향','위스키','입문자'] },
    { kr:'아란 셰리 캐스크', en:'Arran Sherry Cask', g30:28, g60:50, tags:['달콤한','과일향','위스키'] },
    { kr:'아란 소테른 캐스크', en:'Arran Sauternes Cask', g30:28, g60:50, tags:['달콤한','과일향','위스키'] },
    { kr:'아란 포트 캐스크', en:'Arran Port Cask', g30:28, g60:50, tags:['달콤한','과일향','위스키'] },
    { kr:'아란 아마로네 캐스크', en:'Arran Amarone Cask', g30:28, g60:50, tags:['달콤한','강렬한','위스키'] },
    { kr:'아란 13Y 프라이빗 캐스크 코리안 에디션', en:'Arran 13Y Private Cask Korean Ed.', g30:50, g60:90, tags:['달콤한','강렬한','위스키'] },
    { kr:'아란 마크리무어', en:'Arran Machrie Moor', g30:27, g60:49, tags:['스모키','달콤한','위스키'] },
    { kr:'아란 마크리무어 CS', en:'Arran Machrie Moor CS', g30:33, g60:59, tags:['스모키','강렬한','위스키'] },
  ],
  'AMERICAN': [
    { kr:'잭다니엘', en:"Jack Daniel's", g30:13, g60:23, tags:['달콤한','부드러운','위스키','입문자'] },
    { kr:'메이커스 마크', en:"Maker's Mark", g30:12, g60:22, tags:['달콤한','부드러운','위스키','입문자'] },
    { kr:'와일드 터키 8Y', en:'Wild Turkey 8Y', g30:12, g60:22, tags:['달콤한','위스키'] },
    { kr:'와일드 터키 라이', en:'Wild Turkey Rye', g30:15, g60:27, tags:['강렬한','위스키'] },
    { kr:'와일드 터키 레어브리드', en:'Wild Turkey Rare Breed', g30:22, g60:40, tags:['달콤한','강렬한','위스키'] },
    { kr:'와일드 터키 레어브리드 라이', en:'Wild Turkey Rare Breed Rye', g30:25, g60:45, tags:['강렬한','위스키'] },
    { kr:'러셀 리저브 10Y', en:"Russell's Reserve 10Y", g30:16, g60:29, tags:['달콤한','위스키'] },
    { kr:'러셀 싱글배럴', en:"Russell's Single Barrel", g30:20, g60:36, tags:['달콤한','강렬한','위스키'] },
    { kr:'러셀 라이', en:"Russell's Rye", g30:22, g60:40, tags:['강렬한','위스키'] },
    { kr:'불렛 버번', en:'Bullet Bourbon', g30:13, g60:23, tags:['달콤한','위스키','입문자'] },
    { kr:'불렛 라이', en:'Bullet Rye', g30:13, g60:23, tags:['강렬한','위스키'] },
    { kr:'버팔로 트레이스', en:'Buffalo Trace', g30:13, g60:23, tags:['달콤한','부드러운','위스키','입문자'] },
    { kr:'래빗 홀', en:'Rabbit Hole', g30:23, g60:41, tags:['달콤한','위스키'] },
    { kr:'남크릭', en:'Knob Creek', g30:16, g60:29, tags:['달콤한','강렬한','위스키'] },
    { kr:'우드포드 리저브', en:'Woodford Reserve', g30:20, g60:36, tags:['달콤한','위스키'] },
    { kr:'우드포드 리저브 라이', en:'Woodford Reserve Rye', g30:20, g60:36, tags:['강렬한','위스키'] },
    { kr:'포로지스 싱글배럴', en:'Four Roses Single Barrel', g30:17, g60:31, tags:['달콤한','과일향','위스키'] },
    { kr:'휘슬피그 10Y', en:'Whistlepig 10Y', g30:25, g60:45, tags:['강렬한','위스키'] },
    { kr:'노아스밀', en:"Noah's Mill", g30:35, g60:63, tags:['달콤한','강렬한','위스키'] },
    { kr:'올드 에즈라 7Y 배럴 스트렝스 버번', en:'Old Ezra 7Y Barrel Strength Bourbon', g30:35, g60:63, tags:['달콤한','강렬한','위스키'] },
    { kr:'올드 에즈라 7Y 배럴 스트렝스 라이', en:'Old Ezra 7Y Barrel Strength Rye', g30:33, g60:59, tags:['강렬한','위스키'] },
    { kr:'부커스 Batch 2026 01E', en:"Booker's Batch 2026 01E", g30:40, g60:72, tags:['달콤한','강렬한','위스키'] },
    { kr:'1792 스몰 배치', en:'1792 Small Batch', g30:18, g60:32, tags:['달콤한','위스키'] },
    { kr:'1792 풀 푸르프', en:'1792 Full Proof', g30:28, g60:50, tags:['달콤한','강렬한','위스키'] },
    { kr:'엔젤스 엔비', en:"Angel's Envy", g30:17, g60:31, tags:['달콤한','과일향','위스키'] },
    { kr:'이글레어', en:'Eglair', g30:25, g60:45, tags:['달콤한','위스키'] },
    { kr:'웰러 12Y', en:'Weller 12Y', g30:36, g60:65, tags:['달콤한','부드러운','위스키'] },
    { kr:'E.H 테일러', en:'E.H. Taylor', g30:40, g60:73, tags:['달콤한','강렬한','위스키'] },
  ],
  'CAMPBELTOWN': [
    { kr:'글렌스코시아 10Y', en:'GlenScotia 10Y', g30:20, g60:36, tags:['달콤한','스모키','위스키','입문자'] },
    { kr:'글렌스코시아 15Y', en:'GlenScotia 15Y', g30:33, g60:null, tags:['달콤한','스모키','위스키'] },
    { kr:'글렌스코시아 빅토리아나', en:'GlenScotia Victoriana', g30:37, g60:67, tags:['달콤한','강렬한','위스키'] },
    { kr:'글렌스코시아 21Y', en:'Glen Scotia 21Y', g30:150, g60:null, tags:['달콤한','강렬한','위스키'] },
    { kr:'캠벨타운 로크', en:'Campbeltown Loch', g30:25, g60:null, tags:['달콤한','위스키'] },
    { kr:'킬커란 12Y', en:'Kilkerran 12Y', g30:40, g60:null, tags:['달콤한','스모키','위스키'] },
    { kr:'킬커란 16Y', en:'Kilkerran 16Y', g30:50, g60:null, tags:['달콤한','강렬한','위스키'] },
    { kr:'킬커란 CS', en:'Kilkerran CS', g30:45, g60:null, tags:['강렬한','스모키','위스키'] },
    { kr:'스프링뱅크 10Y', en:'Springbank 10Y', g30:40, g60:null, tags:['달콤한','스모키','위스키'] },
    { kr:'스프링뱅크 100 프루프 5Y', en:'Springbank 100 Proof 5Y', g30:35, g60:null, tags:['스모키','강렬한','위스키'] },
    { kr:'스프링뱅크 12Y CS', en:'Springbank 12Y CS', g30:60, g60:null, tags:['스모키','강렬한','위스키'] },
    { kr:'롱로우 피티드', en:'Longrow Peated', g30:40, g60:null, tags:['스모키','강렬한','위스키'] },
  ],
  'OTHER': [
    { kr:'카바란 올로로소 셰리 오크', en:'Kavalan Oloroso Sherry Oak', g30:40, g60:72, tags:['달콤한','강렬한','위스키'] },
    { kr:'카바란 솔리스트 올로로소 셰리 캐스크', en:'Kavalan Solist Oloroso Sherry Cask', g30:45, g60:81, tags:['달콤한','강렬한','위스키'] },
    { kr:'카바란 솔리스트 비노바리끄', en:'Kavalan Solist Vinho Barrique', g30:45, g60:81, tags:['달콤한','강렬한','위스키'] },
    { kr:'알프레드 지로 헤리티지', en:'Alfred Giraud Heritage', g30:33, g60:59, tags:['달콤한','과일향','위스키'] },
    { kr:'알프레드 지로 하모니', en:'Alfred Giraud Harmonic', g30:38, g60:68, tags:['달콤한','위스키'] },
    { kr:'암룻 퓨전', en:'Amrut Fusion', g30:23, g60:41, tags:['달콤한','스모키','위스키'] },
    { kr:'암룻 인디언', en:'Amrut Indian', g30:27, g60:49, tags:['달콤한','위스키'] },
    { kr:'암룻 피티드 인디언 CS', en:'Amrut Peated Indian CS', g30:27, g60:49, tags:['스모키','강렬한','위스키'] },
    { kr:'폴존 PX', en:'Paul John PX', g30:25, g60:45, tags:['달콤한','과일향','위스키'] },
    { kr:'폴존 올로로소', en:'Paul John Oloroso', g30:28, g60:50, tags:['달콤한','위스키'] },
  ],
  'BLENDED': [
    { kr:'몽키숄더', en:'Monkey Shoulder', g30:12, g60:22, tags:['달콤한','부드러운','위스키','입문자'] },
    { kr:'조니워커 더블블랙', en:'Johnnie Walker Double Black', g30:15, g60:27, tags:['달콤한','스모키','위스키','입문자'] },
    { kr:'조니워커 블루라벨', en:'Johnnie Walker Blue Label', g30:50, g60:90, tags:['달콤한','부드러운','강렬한','위스키'] },
    { kr:'로얄 살루트 21Y', en:'Royal Salute 21Y', g30:38, g60:69, tags:['달콤한','부드러운','위스키'] },
    { kr:'혜도니즘', en:'Compass Box Hedonism', g30:48, g60:null, tags:['달콤한','부드러운','위스키'] },
    { kr:'브륄레 로얄', en:'Compass Box Brûlée Royale', g30:55, g60:null, tags:['달콤한','위스키'] },
  ],
  'JAPANESE': [
    { kr:'닛카 요이치', en:'Nikka Yoichi', g30:22, g60:40, tags:['스모키','강렬한','위스키'] },
    { kr:'닛카 미야기쿄', en:'Nikka Miyagikyo', g30:22, g60:40, tags:['달콤한','과일향','부드러운','위스키'] },
    { kr:'하쿠슈 12 100주년', en:'Hakushu 12 100th Anniversary', g30:45, g60:null, tags:['스모키','과일향','위스키'] },
    { kr:'히비키 하모니', en:'Hibiki Harmony', g30:30, g60:54, tags:['달콤한','과일향','부드러운','위스키','입문자'] },
    { kr:'히비키 하모니 마스터 셀렉', en:'Hibiki Harmony Master Select', g30:45, g60:81, tags:['달콤한','부드러운','위스키'] },
    { kr:'야마자키 12Y', en:'Yamazaki 12Y', g30:40, g60:72, tags:['달콤한','과일향','부드러운','위스키'] },
    { kr:'아케시 소한', en:'Akkeshi Sokan', g30:55, g60:99, tags:['스모키','강렬한','위스키'] },
    { kr:'이치로스 몰트 앤 그레인', en:"Ichiro's Malt & Grain", g30:36, g60:65, tags:['달콤한','과일향','위스키'] },
  ],
  'SPECIAL & IB': [
    { kr:'제기 (JEGI – Craftbros × Highcost)', en:'JEGI', g30:30, g60:54, tags:['달콤한','위스키'] },
    { kr:'글렌 알라키 17Y', en:'GlenAllachie 17Y', g30:45, g60:null, tags:['달콤한','강렬한','위스키'] },
    { kr:'스페이사이드(M) 14년 #16 스몰 배치', en:'Speyside 2010 14Y #16 Small Batch', g30:35, g60:63, tags:['달콤한','위스키'] },
    { kr:'부나하벤 스토이사 11Y 이비스코 디켄터', en:'Bunnahabhain Staoisha 2013 11Y Ibisco Decante', g30:33, g60:59, tags:['스모키','달콤한','위스키'] },
    { kr:'트랜스컨티넨탈 럼라인 니카라과', en:'Transcontinental RumLine Nicaragua', g30:35, g60:63, tags:['달콤한','과일향','위스키'] },
    { kr:'보리밭을 흔드는 바람', en:'Barley Field Wind', g30:40, g60:72, tags:['달콤한','위스키'] },
  ],
};

// ─── FOOD ────────────────────────────────────────────────────────────────────
const FOOD = {
  'First Pair — 첫 잔과 함께': [
    { kr:'토마토 모짜', en:'Olive, Tomato & Mozzarella', price:'₩18,000', desc:'산뜻하고 깔끔한 맛으로 첫 잔이나 가벼운 스페이사이드 위스키와 추천드립니다.' },
    { kr:'브리치즈 구이', en:'Baked Brie Cheese', price:'₩25,000', desc:'셰리 캐스크의 달콤하고 풍부한 위스키와 훌륭한 조화를 이룹니다.' },
  ],
  'Perfect Pair — 잔이 비워질 즈음': [
    { kr:'치즈 & 샤퀴테리 플래터', en:'Cheese & Charcuterie Platter', price:'₩35,000', desc:'위스키의 풍미를 잘 살려주는 가장 클래식한 페어링입니다.' },
    { kr:'소세지 플래터', en:'Sausage Platter', price:'₩20,000', desc:'훈연향과 육즙이 버번이나 가벼운 하이볼과 잘 어울립니다.' },
    { kr:'똠얌 신라면', en:'Ramen (Thai style)', price:'₩8,000', desc:'익숙한 신라면에 태국의 향을 더해 깊은 풍미의 스파이시 누들로, 깔끔한 하이볼이나 맥주와 드셔보세요.' },
  ],
  'Sweet Finish — 마지막 한 잔': [
    { kr:'츄러스 엔 딥', en:'Churros & Dip (6ea)', price:'₩15,000', desc:'버번과 디저트 스타일 위스키의 바닐라 향을 더욱 돋보이게 합니다.' },
    { kr:'헤이즐넛 크럼블 아이스크림', en:'Hazelnut Crumble Ice Cream', price:'₩13,000', desc:'피트의 스모키함이나 셰리의 달콤함과 즐기기 좋은 마무리 디저트입니다.' },
  ],
};

// ─── TASTING COURSES ─────────────────────────────────────────────────────────
const TASTING = [
  { num:'NO. 1', name:'Indian', price:'₩45,000', items:'Amrut Fusion / Paul John PX / Paul John Oloroso', desc:'인도 위스키 세 가지로, 스코틀랜드 밖에도 위스키가 있다는 것을 확인하는 코스입니다.' },
  { num:'NO. 2', name:'Peat', price:'₩38,000', items:'Ardbeg An Oa / Kilchoman Sanaig / Laphroaig Select', desc:'스모키가 무엇인지 궁금하셨던 분을 위한, 아일라 피트 입문 코스입니다.' },
  { num:'NO. 3', name:'The Peat Monster', price:'₩99,000', items:'Ardbeg Traigh Bhan 19Y / LAGG Batch / Octomore 15.3', desc:'피트의 끝까지 가보고 싶은 분을 위한 코스입니다. 옥토모어를 포함합니다.' },
  { num:'NO. 4', name:'Sweet', price:'₩50,000', items:'GlenAllachie 12Y Moscatel / Glenmorangie Quinta Ruban / Arran Port Cask', desc:'각기 다른 와인 캐스크가 만들어내는 단맛의 결을 비교하는 코스입니다.' },
  { num:'NO. 5', name:'Campbeltown', price:'₩69,000', items:'Springbank 100 Proof 5Y / Longrow Peated / Kilkerran 12Y', desc:'캠벨타운 세 증류소를 나란히 비교하는, 국내에서도 흔치 않은 코스입니다.' },
  { num:'NO. 6', name:'Asia', price:'₩52,000', items:'JEGI / Kavalan Oloroso Sherry Oak / Nikka Miyagikyo', desc:'한국·대만·일본. 아시아 위스키의 차이를 확인하는 코스입니다.' },
  { num:'No. 7', name:'Port', price:'₩57,000', items:'Kranemann Tawny 10 / 20 / 30', desc:'오래된 목재 캐스크에서 숙성하여, 숙성 연수에 따른 풍미와 복합미의 차이를 느낄 수 있습니다.' },
];

// ─── BOTTLE ──────────────────────────────────────────────────────────────────
const BOTTLE = [
  { kr:'글렌리벳 12년', en:'The Glenlivet 12Y', price:'₩300,000' },
  { kr:'글렌리벳 15년', en:'The Glenlivet 15Y', price:'₩450,000' },
  { kr:'글렌피딕 12년', en:'Glenfiddich 12Y', price:'₩330,000' },
  { kr:'글렌피딕 15년', en:'Glenfiddich 15Y', price:'₩460,000' },
  { kr:'글렌모렌지 오리지널', en:'Glenmorangie Original', price:'₩300,000' },
  { kr:'글렌모렌지 라산타', en:'Glenmorangie Lasanta', price:'₩470,000' },
  { kr:'발베니 12년', en:'The Balvenie 12Y', price:'₩360,000' },
  { kr:'발베니 14년', en:'The Balvenie 14Y', price:'₩550,000' },
  { kr:'달모어 12년', en:'The Dalmore 12Y', price:'₩390,000' },
  { kr:'달모어 12년 셰리', en:'The Dalmore 12Y Sherry Cask', price:'₩520,000' },
  { kr:'달모어 15년', en:'The Dalmore 15Y', price:'₩650,000' },
  { kr:'글렌알라키 12년', en:'GlenAllachie 12Y', price:'₩420,000' },
  { kr:'조니워커 블루', en:'Johnnie Walker Blue Label', price:'₩820,000' },
  { kr:'이글레어 10년', en:'Eagle Rare 10Y', price:'₩460,000' },
  { kr:'버팔로 트레이스', en:'Buffalo Trace', price:'₩240,000' },
];

// ─── OTHER DRINKS ─────────────────────────────────────────────────────────────
const OTHER = {
  'COGNAC': [
    { kr:'헤네시 XO', en:'Hennessy XO', g30:60, g60:109 },
    { kr:'헤네시 VSOP', en:'Hennessy VSOP', g30:25, g60:45 },
    { kr:'마르텔 VSOP', en:'Martell VSOP', g30:18, g60:32 },
    { kr:'까뮤 보더리 XO', en:'Camus Borderies XO', g30:55, g60:99 },
  ],
  'PORT WINE': [
    { kr:'크레인만 타우니 10년', en:'Kranemann Tawny 10Y', g30:15, g60:27 },
    { kr:'크레인만 타우니 20년', en:'Kranemann Tawny 20Y', g30:25, g60:45 },
    { kr:'크레인만 타우니 30년', en:'Kranemann Tawny 30Y', g30:55, g60:99 },
  ],
  'GIN': [
    { kr:'탱커레이', en:'Tanqueray', g30:13, g60:23 },
    { kr:'헨드릭스 진', en:"Hendrick's Gin", g30:20, g60:36 },
    { kr:'몽키47', en:'Monkey 47', g30:20, g60:36 },
    { kr:'크리스찬 드루앵 르 진', en:'Christian Drouin Le Gin', g30:25, g60:45 },
    { kr:'더 보타니스트', en:'The Botanist', g30:18, g60:32 },
    { kr:'포필리스 진 크리스마스 에디션', en:'Populis Gin Christmas Edition', g30:24, g60:43 },
  ],
  'TEQUILA': [
    { kr:'신코로 레포사도', en:'Cincoro Reposado', g30:35, g60:63 },
    { kr:'신코로 아네호', en:'Cincoro Añejo', g30:40, g60:72 },
  ],
  'RUM': [
    { kr:'에미넨테 럼', en:'Eminente Reserva Rum', g30:23, g60:41 },
    { kr:'니카라과 럼', en:'Nicaraguan Rum', g30:35, g60:63 },
    { kr:'디플로마티코', en:'Diplomatico', g30:18, g60:32 },
    { kr:'골드 오브 모리서스', en:'Gold of Mauritius Black 48', g30:18, g60:32 },
  ],
  'BEER': [
    { kr:'포쉐트', en:'Fourchette', price:'₩18,000', desc:'미슐랭 스타 셰프와 벨기에 반스틴베르그 양조장이 협업한 트리펠 스타일 맥주. 시트러스·꽃향과 부드러운 단맛. 330ml · 7.5%' },
  ],
  'CALVADOS': [
    { kr:'크리스찬 드루앵 르 진', en:'Christian Drouin Le Gin', g30:25, g60:45 },
    { kr:'크리스찬 드루앵 XO', en:'Christian Drouin XO', g30:28, g60:50 },
    { kr:'크리스찬 드루앵 뽐 프리지니에르', en:"Calvados Pays d'Auge Pomme Prisonnière", g30:40, g60:72 },
    { kr:'크리스찬 드루앵 × 치치부 엔젤스', en:'Christian Drouin × Chichibu Angels Experimental #11', g30:45, g60:81 },
    { kr:'드루앵 밀레지메 2003', en:'Les Millésimes de Christian Drouin 2003', g30:45, g60:81 },
    { kr:'드루앵 밀레지메 2004', en:'Les Millésimes de Christian Drouin 2004', g30:50, g60:90 },
    { kr:'드루앵 밀레지메 2005', en:'Les Millésimes de Christian Drouin 2005', g30:47, g60:85 },
  ],
  'CIDRE': [
    { kr:'크리스찬 드루앵 시드르 브뤼', en:'Christian Drouin Cidre Brut', price:'₩60,000', desc:'사과를 착즙 후 겨울 동안 자연 발효시켜 탄산가스를 주입한 노르망디 지역의 전통 발효주. 은은한 사과 향과 기분 좋은 산미. 750ml · Alc. 4.5%' },
    { kr:'크리스찬 드루앵 뽀아레', en:'Christian Drouin Poiré', price:'₩80,000', desc:'배 주스를 발효하는 과정에서 자연스러운 기포가 생기는 노르망디 지역의 배 발효주. 식전주로 가볍고 상쾌하게 즐기기 좋습니다. 750ml · Alc. 4.0%' },
  ],
};
