// ═══════════════════════════════════════════════════════════════════
// Uisce Beatha — Google Sheets 자동 세팅 스크립트
// 사용법: Google Apps Script 에디터에 붙여넣고 setupMenu() 실행
// ═══════════════════════════════════════════════════════════════════

function setupMenu() {
  const ss = SpreadsheetApp.getActiveSpreadsheet();

  setupSheet(ss, 'SIGNATURE', [
    ['한국어','영어','가격','설명','도수','태그'],
    ['카카오 벨벳','Cacao Velvet',25,'부드러운 크림과 달콤한 카카오의 조화, 코코넛 워터가 깔끔하게 마무리해주는 디저트 스타일 칵테일','Alc. 18-20%','달콤한,부드러운,칵테일,중간'],
    ['망고 오! 망고','Mango OH! Mango',20,'망고를 베이스로 상큼함과 청량감을 더한 하이볼','Alc. 8-10%','상큼한,과일향,탄산있는,가볍게,칵테일'],
    ['베리 요거트','Berry Yogurt',19,'복분자의 진한 풍미에 요거트의 부드러움을 더한 새콤달콤한 디저트 스타일 칵테일','Alc. 8-10%','달콤한,상큼한,과일향,부드러운,가볍게,칵테일'],
  ]);

  setupSheet(ss, 'COCKTAIL', [
    ['카테고리','한국어','영어','가격','설명','도수','태그'],
    ['GIN','진 피즈','Gin Fizz',18,'상큼한 레몬과 진, 톡 쏘는 탄산이 어우러진 클래식한 청량 칵테일','Alc. 12-16%','상큼한,탄산있는,가볍게,칵테일'],
    ['GIN','진 토닉','Gin Tonic',15,'진의 향긋함과 토닉워터의 쌉쌀함이 완벽한 조화를 이루는 시그니처 하이볼','Alc. 10-15%','쌉쌀한,탄산있는,가볍게,칵테일,입문자'],
    ['GIN','진 리키','Gin Rickey',16,'설탕 없이 깔끔하게, 라임과 탄산이 진의 풍미를 돋우는 드라이한 칵테일','Alc. 10-15%','상큼한,탄산있는,가볍게,칵테일'],
    ['GIN','김렛','Gimlet',18,'진과 라임이 빚어낸 단순하지만 우아한, 단맛과 산미의 균형이 매력적인 칵테일','Alc. 20-25%','달콤한,상큼한,중간,칵테일'],
    ['GIN','드라이 마티니','Dry Martini',20,'진과 드라이 베르무트가 만드는 가장 간결하고 도회적인 클래식','Alc. 30-35%','쌉쌀한,강렬한,강하게,칵테일'],
    ['GIN','네그로니','Negroni',20,'진, 캄파리, 스위트 베르무트가 어우러진 쌉쌀한 매력의 이탈리안 클래식','Alc. 24-28%','쌉쌀한,강렬한,중간,칵테일'],
    ['VODKA','롱 티','Long Island Iced Tea',18,'칵테일 계의 폭탄주, 이름과 달리 강렬한 한 잔','Alc. 20-22%','강렬한,중간,칵테일'],
    ['VODKA','우스케 뮬','Uisce Mule',18,'진저비어의 풍미와 시트러스 향을 느낄 수 있는 위스키가 어우러진 시원한 칵테일','Alc. 11-15%','상큼한,탄산있는,가볍게,칵테일,입문자'],
    ['VODKA','블랙 러시안','Black Russian',20,'보드카와 커피 리큐르가 만든, 묵직하고 부드러운 단맛의 칵테일','Alc. 20-25%','달콤한,쌉쌀한,중간,칵테일'],
    ['VODKA','에스프레소 마티니','Espresso Martini',20,'보드카와 에스프레소, 커피 리큐르의 조화로 완성된 깔끔하고 진한 커피 칵테일','Alc. 20-25%','쌉쌀한,중간,칵테일'],
    ['RUM','다이키리','Daiquiri',22,'럼과 라임, 설탕이 빚어낸 클래식한 산뜻함. 단순함 속의 균형','Alc. 20-25%','상큼한,중간,칵테일'],
    ['RUM','모히또','Mojito',18,'민트와 라임, 럼이 어우러진 청량한 여름의 한 잔','Alc. 10-15%','상큼한,탄산있는,가볍게,칵테일,입문자'],
    ['RUM','럼 올드패션','Rum Old Fashioned',25,'럼의 깊은 풍미에 설탕과 비터스가 어우러진, 부드럽고 묵직한 클래식','Alc. 30-35%','달콤한,부드러운,강렬한,강하게,칵테일'],
    ['CALVADOS','칼바도스 진 리키','Calvados Gin Rickey',19,'칼바도스와 진, 라임, 탄산이 어우러져 사과 향이 은은하게 퍼지는 드라이한 리키','Alc. 10-15%','상큼한,과일향,탄산있는,가볍게,칵테일'],
    ['CALVADOS','칼바도스 진 피즈','Calvados Gin Fizz',21,'청사과의 상쾌함을 담은 칼바도스와 진, 레몬, 탄산이 만난 부드러운 피즈','Alc. 12-18%','상큼한,과일향,탄산있는,가볍게,칵테일'],
    ['CALVADOS','칼바도스 김렛','Calvados Gimlet',22,'칼바도스의 과실 향과 라임의 산미가 진과 어우러져 과일 풍미가 살아나는 김렛','Alc. 20-25%','달콤한,상큼한,과일향,중간,칵테일'],
    ['CALVADOS','노르망디','Normandy',24,'칼바도스와 드라이 베르무트, 오렌지 비터스가 어우러진, 우아한 사과향 클래식','Alc. 18-20%','달콤한,과일향,중간,칵테일'],
    ['CALVADOS','허니문','Honeymoon',25,'허브의 은은한 달콤함과 상큼한 산미가 어우러진 부드럽고 균형 잡힌 클래식 칵테일','Alc. 18-22%','달콤한,부드러운,중간,칵테일'],
    ['CALVADOS','칼바도스 소닉','Calvados Sonic',22,'가볍고 청량한 탄산감에 은은한 과일 향이 더해진 산뜻한 하이볼 스타일','Alc. 10-14%','상큼한,과일향,탄산있는,가볍게,칵테일'],
    ['WHISKEY','위스키 하이볼','Whiskey Highball',18,'위스키와 탄산수로만 완성되는 칵테일','','탄산있는,부드러운,가볍게,칵테일,입문자'],
    ['WHISKEY','위스키 사워','Whiskey Sour',22,'버번과 레몬, 설탕이 어우러진 새콤달콤한 위스키 입문자용 클래식','Alc. 15-20%','달콤한,상큼한,중간,칵테일,입문자'],
    ['WHISKEY','아마레또 사워','Amaretto Sour',22,'아몬드 향의 달콤함과 레몬의 상큼함이 어우러진 부드러운 사워 칵테일','Alc. 20%','달콤한,상큼한,중간,칵테일,입문자'],
    ['WHISKEY','올드 패션','Old Fashioned',22,'설탕과 비터스, 위스키만으로 완성되는 가장 단순하고 가장 묵직한 한 잔','Alc. 30-35%','달콤한,강렬한,강하게,칵테일'],
    ['WHISKEY','갓파더','GodFather',22,'스카치와 아마레또가 만나 강렬함 속에 은근한 단맛을 더한 매혹적인 칵테일','Alc. 25-30%','달콤한,강렬한,강하게,칵테일'],
    ['WHISKEY','맨하탄','Manhattan',24,'라이 위스키와 스위트 베르무트, 비터스가 어우러진 우아하고 절제된 클래식','Alc. 28%','달콤한,강렬한,강하게,칵테일'],
    ['WHISKEY','리볼버','Revolver',22,'버번과 커피 리큐르, 오렌지 비터가 어우러진 스모키한 향의 위스키 마티니','Alc. 30-35%','쌉쌀한,강렬한,강하게,칵테일'],
    ['WHISKEY','사제락','Sazerac',23,'페이쇼 비터와 압샌트의 아로마가 위스키에 스며든, 뉴올리언스 스타일의 헤리티지 칵테일','Alc. 35%','강렬한,강하게,칵테일'],
    ['WHISKEY','하이랜드 쿨러','Highland Cooler',20,'스카치의 풍미에 생강과 레몬이 더해진 상쾌한 위스키 하이볼','Alc. 10-15%','상큼한,탄산있는,가볍게,칵테일'],
    ['WHISKEY','페니실린','Penicillin',22,'스모키한 위스키와 생강, 꿀, 레몬이 어우러진 따뜻하면서도 강렬한 한 잔','Alc. 20-25%','스모키,달콤한,상큼한,중간,칵테일'],
    ['WHISKEY','초크 앤 스모크','Choke and Smoke',22,'탈리스커 기주의 클래식한 칵테일','Alc. 40%','스모키,강렬한,강하게,칵테일'],
    ['LIQUER','카카오 피즈','Cacao Fizz',18,'카카오의 달콤 쌉쌀함과 탄산의 청량함이 어우러진 디저트 같은 칵테일','Alc. 6%','달콤한,쌉쌀한,탄산있는,가볍게,칵테일,입문자'],
    ['LIQUER','에프리콧 피즈','Apricot Fizz',19,'살구 리큐르의 은은한 단맛과 산뜻한 거품이 어우러지는 상큼한 한 잔','Alc. 10-15%','달콤한,상큼한,과일향,탄산있는,가볍게,칵테일'],
    ['LIQUER','엘더플라워 피즈','Elderflower Fizz',21,'꽃향 가득한 엘더플라워와 탄산이 어우러진, 은은하고 청량한 한 잔','Alc. 10-15%','달콤한,과일향,탄산있는,가볍게,칵테일'],
    ['BRANDY','사이드카','SideCar',25,'브랜디, 트리플 섹, 레몬 주스의 조화로 탄생한 달콤쌉싸름한 황금빛 한 잔','Alc. 22-30%','달콤한,상큼한,중간,칵테일'],
    ['BRANDY','프렌치 커넥션','French Connection',25,'코냑과 아마레또가 어우러진 달콤하고 부드러운 클래식 칵테일','Alc. 30-34%','달콤한,부드러운,강하게,칵테일'],
    ['BRANDY','어텀 리브스','Autumn Leaves',24,'허브의 깊은 달콤함에 은은한 스파이스와 부드러운 버번의 따뜻함이 느껴지는 칵테일','Alc. 28-32%','달콤한,부드러운,강하게,칵테일'],
    ['BRANDY','피스코 사워','Pisco Sour',22,'부드러운 거품과 함께 상큼한 산미와 은은한 단맛이 조화로운 클래식 칵테일','Alc. 18-22%','상큼한,달콤한,부드러운,중간,칵테일'],
    ['APEROL','아페롤 피즈','Aperol Fizz',21,'가볍고 부드러운 탄산감에 은은한 시트러스 향이 더해진 산뜻하고 청량한 한 잔','Alc. 10-15%','상큼한,쌉쌀한,탄산있는,가볍게,칵테일,입문자'],
    ['APEROL','아페롤 토닉','Aperol Tonic',21,'쌉쌀함과 상큼한 향이 어우러진, 가볍게 즐기기 좋은 청량한 하이볼 스타일','Alc. 10-15%','쌉쌀한,탄산있는,가볍게,칵테일,입문자'],
    ['APEROL','아페롤 네그로니','Aperol Negroni',25,'쌉쌀함과 오렌지 계열의 향이 부드럽게 이어지는 밸런스 좋은 네그로니','Alc. 20-25%','쌉쌀한,과일향,중간,칵테일'],
    ['COFFEE','사케라또','Shakerato',8,'에스프레소를 차갑게 흔들어낸, 진한 커피 향과 시원한 쌉쌀함이 매력적인 이탈리안 아이스 커피. 위스키와 페어링을 추천합니다.','','쌉쌀한,가볍게'],
  ]);

  setupSheet(ss, 'WHISKEY', [
    ['지역','한국어','영어','30ml가격','60ml가격','태그'],
    ['SPEYSIDE','글렌피딕 12Y','Glenfiddich 12Y',16,29,'달콤한,과일향,부드러운,위스키,입문자'],
    ['SPEYSIDE','글렌피딕 15Y','Glenfiddich 15Y',27,49,'달콤한,과일향,부드러운,위스키'],
    ['SPEYSIDE','글렌피딕 16Y 에스터 마틴','Glenfiddich 16Y',29,57,'달콤한,과일향,위스키'],
    ['SPEYSIDE','글렌피딕 18Y','Glenfiddich 18Y',41,74,'달콤한,과일향,부드러운,위스키'],
    ['SPEYSIDE','글렌알라키 10Y CS','Glen Allachie 10Y Batch 10 CS',30,57,'달콤한,강렬한,위스키'],
    ['SPEYSIDE','글렌알라키 10Y 모스카텔','Glen Allachie 10Y Moscatel',30,54,'달콤한,과일향,위스키'],
    ['SPEYSIDE','글렌알라키 11Y','Glen Allachie 11Y',37,67,'달콤한,위스키'],
    ['SPEYSIDE','글렌알라키 12Y','Glen Allachie 12Y',23,42,'달콤한,부드러운,위스키,입문자'],
    ['SPEYSIDE','글렌알라키 15Y','Glen Allachie 15Y',35,63,'달콤한,위스키'],
    ['SPEYSIDE','글렌알라키 18Y','Glen Allachie 18Y',50,90,'달콤한,강렬한,위스키'],
    ['SPEYSIDE','미클토어 더 오리지널','Meikle Toir The Original',23,41,'스모키,위스키'],
    ['SPEYSIDE','미클토어 더 셰리 원','Meikle Toir The Sherry One',25,45,'달콤한,스모키,위스키'],
    ['SPEYSIDE','미클토어 터보','Meikle Toir The Turbo',25,45,'스모키,강렬한,위스키'],
    ['SPEYSIDE','맥네어스 럼릭 12Y',"MacNair's Lum Reek 12Y",20,36,'스모키,달콤한,위스키'],
    ['SPEYSIDE','맥네어스 럼릭 10Y CS',"MacNair's Lum Reek 10Y CS",28,51,'스모키,강렬한,위스키'],
    ['SPEYSIDE','더 글렌리벳 12Y','The Glenlivet 12Y',16,29,'달콤한,과일향,부드러운,위스키,입문자'],
    ['SPEYSIDE','더 글렌리벳 15Y','The Glenlivet 15Y',25,45,'달콤한,과일향,위스키'],
    ['SPEYSIDE','더 글렌리벳 18Y','The Glenlivet 18Y',42,76,'달콤한,과일향,부드러운,위스키'],
    ['SPEYSIDE','탐듀 12Y','Tamdhu 12Y',18,32,'달콤한,위스키,입문자'],
    ['SPEYSIDE','탐듀 15Y','Tamdhu 15Y',33,59,'달콤한,위스키'],
    ['SPEYSIDE','탐듀 18Y','Tamdhu 18Y',50,90,'달콤한,강렬한,위스키'],
    ['SPEYSIDE','맥캘란 12Y 더블 오크 캐스크','Macallan 12Y Double Oak Cask',20,36,'달콤한,부드러운,위스키,입문자'],
    ['SPEYSIDE','맥캘란 12Y 셰리 오크 캐스크','Macallan 12Y Sherry Oak Cask',27,49,'달콤한,과일향,위스키'],
    ['SPEYSIDE','맥캘란 15Y 더블캐스크','Macallan 15Y Double Cask',35,62,'달콤한,부드러운,위스키'],
    ['SPEYSIDE','맥캘란 18Y 셰리 오크 캐스크','Macallan 18Y Sherry Oak Cask',55,99,'달콤한,강렬한,위스키'],
    ['SPEYSIDE','발베니 12Y 싱글 배럴','Balvenie 12Y Single Barrel',25,45,'달콤한,과일향,위스키'],
    ['SPEYSIDE','발베니 12Y 더블우드','Balvenie 12Y Double Wood',19,35,'달콤한,부드러운,위스키,입문자'],
    ['SPEYSIDE','발베니 12Y 아메리칸 오크','Balvenie 12Y American Oak',25,45,'달콤한,위스키'],
    ['SPEYSIDE','발베니 14Y 캐리비안 캐스크','Balvenie 14Y Caribbean Cask',33,60,'달콤한,과일향,위스키'],
    ['SPEYSIDE','발베니 16Y 프렌치오크','Balvenie 16Y French Oak',42,76,'달콤한,과일향,위스키'],
    ['SPEYSIDE','벤로막 10Y','Benromach 10Y',16,29,'달콤한,스모키,위스키,입문자'],
    ['SPEYSIDE','벤로막 15Y','Benromach 15Y',33,59,'달콤한,스모키,위스키'],
    ['SPEYSIDE','아벨라위 12Y','Aberlour 12Y',21,38,'달콤한,과일향,위스키'],
    ['SPEYSIDE','아벨라위 아부나흐',"Aberlour A'bunadh",32,58,'달콤한,강렬한,위스키'],
    ['HIGHLAND','글렌모렌지 오리지널','Glenmorangie The Original',19,35,'달콤한,과일향,부드러운,위스키,입문자'],
    ['HIGHLAND','글렌모렌지 라산타','Glenmorangie Lasanta',28,50,'달콤한,과일향,위스키'],
    ['HIGHLAND','글렌모렌지 더 넥타','Glenmorangie The Nectar',25,45,'달콤한,과일향,위스키'],
    ['HIGHLAND','글렌모렌지 퀸타 루반','Glenmorangie Quinta Ruban',25,45,'달콤한,과일향,위스키'],
    ['HIGHLAND','글렌모렌지 시그넷','Glenmorangie Signet',45,81,'달콤한,강렬한,위스키'],
    ['HIGHLAND','글렌드로낙 12Y','Glendronach 12Y',18,32,'달콤한,과일향,위스키,입문자'],
    ['HIGHLAND','글렌드로낙 15Y','Glendronach 15Y',33,59,'달콤한,강렬한,위스키'],
    ['HIGHLAND','글렌드로낙 18Y','Glendronach 18Y',45,81,'달콤한,강렬한,위스키'],
    ['HIGHLAND','글렌파클라스 15Y','Glenfarclas 15Y',33,59,'달콤한,위스키'],
    ['HIGHLAND','글렌파클라스 105 CS','Glenfarclas 105 CS',28,50,'달콤한,강렬한,위스키'],
    ['HIGHLAND','달모어 12Y','Dalmore 12Y',21,38,'달콤한,과일향,위스키,입문자'],
    ['HIGHLAND','달모어 12Y 셰리','Dalmore 12Y Sherry',31,56,'달콤한,과일향,위스키'],
    ['HIGHLAND','달모어 15Y','Dalmore 15Y',38,69,'달콤한,강렬한,위스키'],
    ['HIGHLAND','글렌 고인 12Y','Glengoyne 12Y',15,27,'달콤한,부드러운,위스키,입문자'],
    ['HIGHLAND','글렌 고인 15Y','Glengoyne 15Y',27,49,'달콤한,위스키'],
    ['HIGHLAND','글렌 고인 21Y','Glengoyne 21Y',55,'','달콤한,강렬한,위스키'],
    ['HIGHLAND','달위니 15Y','Dalwhinnie 15Y',23,41,'달콤한,부드러운,위스키,입문자'],
    ['HIGHLAND','오반 14Y','Oban 14Y',25,45,'달콤한,스모키,위스키'],
    ['HIGHLAND','글렌 터렛 10Y 피트 스모크드','GlenTurret 10Y Peat Smoked',18,32,'스모키,위스키'],
    ['HIGHLAND','글렌 터렛 12Y','GlenTurret 12Y',25,45,'달콤한,위스키'],
    ['HIGHLAND','에드라두어 발레친 10Y','Ballechin 10Y',28,50,'스모키,강렬한,위스키'],
    ['HIGHLAND','에드라두어 2015 싱글 캐스크','Edradour 2015 Single Cask',35,62,'달콤한,위스키'],
    ['HIGHLAND','에드라두어 11Y 스몰 배치','Edradour 11Y Small Batch',30,54,'달콤한,위스키'],
    ['ISLAY','아드벡 10Y','Ardbeg 10Y',19,35,'스모키,강렬한,위스키'],
    ['ISLAY','아드벡 우가달','Ardbeg Uigeadail',28,50,'스모키,달콤한,강렬한,위스키'],
    ['ISLAY','아드벡 언 오','Ardbeg An Oa',25,45,'스모키,달콤한,위스키'],
    ['ISLAY','아드벡 코리브레칸','Ardbeg Corryvreckan',33,60,'스모키,강렬한,위스키'],
    ['ISLAY','아드벡 위비스티','Ardbeg Wee Beastie',18,32,'스모키,강렬한,위스키'],
    ['ISLAY','아드벡 19Y 트라이 반 배치6','Ardbeg Traigh Bhan Batch 6',40,72,'스모키,강렬한,위스키'],
    ['ISLAY','라가불린 11Y','Lagavulin 11Y',20,36,'스모키,강렬한,위스키'],
    ['ISLAY','라가불린 16Y','Lagavulin 16Y',32,58,'스모키,강렬한,위스키'],
    ['ISLAY','라프로익 10Y','Laphroaig 10Y',16,29,'스모키,강렬한,위스키'],
    ['ISLAY','라프로익 셀렉트','Laphroaig Select',16,29,'스모키,위스키'],
    ['ISLAY','라프로익 쿼터캐스크','Laphroaig Quarter Cask',22,40,'스모키,달콤한,강렬한,위스키'],
    ['ISLAY','보모어 12Y','Bowmore 12Y',16,29,'스모키,달콤한,위스키,입문자'],
    ['ISLAY','보모어 18Y','Bowmore 18Y',35,63,'스모키,달콤한,위스키'],
    ['ISLAY','라세이','Raasay',18,32,'스모키,위스키'],
    ['ISLAY','킬 호만 사닉','Kilchoman Sanaig',23,41,'스모키,강렬한,위스키'],
    ['ISLAY','옥토모어 15.3','Octomore 15.3',85,'','스모키,강렬한,위스키'],
    ['ISLAY','옥토모어 16.3','Octomore 16.3',90,'','스모키,강렬한,위스키'],
    ['ISLAND','탈리스커 10Y','Talisker 10Y',16,29,'스모키,강렬한,위스키'],
    ['ISLAND','탈리스커 10Y Old Bottle','Talisker 10Y Old Bottle',22,'','스모키,강렬한,위스키'],
    ['ISLAND','탈리스커 25Y','Talisker 25Y',90,162,'스모키,강렬한,위스키'],
    ['ISLAND','하이랜드파크 12Y','Highland Park 12Y',18,32,'달콤한,스모키,위스키,입문자'],
    ['ISLAND','하이랜드파크 18Y','Highland Park 18Y',38,68,'달콤한,스모키,위스키'],
    ['ISLAND','라그 배치 1','LAGG Batch 1',35,63,'스모키,달콤한,위스키'],
    ['ISLAND','라그 배치 2','LAGG Batch 2',35,63,'스모키,달콤한,위스키'],
    ['ISLAND','라그 배치 3','LAGG Batch 3',35,63,'스모키,달콤한,위스키'],
    ['ISLAND','아란 10Y','Arran 10Y',18,32,'달콤한,과일향,위스키,입문자'],
    ['ISLAND','아란 셰리 캐스크','Arran Sherry Cask',28,50,'달콤한,과일향,위스키'],
    ['ISLAND','아란 소테른 캐스크','Arran Sauternes Cask',28,50,'달콤한,과일향,위스키'],
    ['ISLAND','아란 포트 캐스크','Arran Port Cask',28,50,'달콤한,과일향,위스키'],
    ['ISLAND','아란 아마로네 캐스크','Arran Amarone Cask',28,50,'달콤한,강렬한,위스키'],
    ['ISLAND','아란 13Y 프라이빗 캐스크 코리안 에디션','Arran 13Y Private Cask Korean Ed.',50,90,'달콤한,강렬한,위스키'],
    ['ISLAND','아란 마크리무어','Arran Machrie Moor',27,49,'스모키,달콤한,위스키'],
    ['ISLAND','아란 마크리무어 CS','Arran Machrie Moor CS',33,59,'스모키,강렬한,위스키'],
    ['AMERICAN','잭다니엘',"Jack Daniel's",13,23,'달콤한,부드러운,위스키,입문자'],
    ['AMERICAN','메이커스 마크',"Maker's Mark",12,22,'달콤한,부드러운,위스키,입문자'],
    ['AMERICAN','와일드 터키 8Y','Wild Turkey 8Y',12,22,'달콤한,위스키'],
    ['AMERICAN','와일드 터키 라이','Wild Turkey Rye',15,27,'강렬한,위스키'],
    ['AMERICAN','와일드 터키 레어브리드','Wild Turkey Rare Breed',22,40,'달콤한,강렬한,위스키'],
    ['AMERICAN','와일드 터키 레어브리드 라이','Wild Turkey Rare Breed Rye',25,45,'강렬한,위스키'],
    ['AMERICAN','러셀 리저브 10Y',"Russell's Reserve 10Y",16,29,'달콤한,위스키'],
    ['AMERICAN','러셀 싱글배럴',"Russell's Single Barrel",20,36,'달콤한,강렬한,위스키'],
    ['AMERICAN','러셀 라이',"Russell's Rye",22,40,'강렬한,위스키'],
    ['AMERICAN','불렛 버번','Bullet Bourbon',13,23,'달콤한,위스키,입문자'],
    ['AMERICAN','불렛 라이','Bullet Rye',13,23,'강렬한,위스키'],
    ['AMERICAN','버팔로 트레이스','Buffalo Trace',13,23,'달콤한,부드러운,위스키,입문자'],
    ['AMERICAN','래빗 홀','Rabbit Hole',23,41,'달콤한,위스키'],
    ['AMERICAN','남크릭','Knob Creek',16,29,'달콤한,강렬한,위스키'],
    ['AMERICAN','우드포드 리저브','Woodford Reserve',20,36,'달콤한,위스키'],
    ['AMERICAN','우드포드 리저브 라이','Woodford Reserve Rye',20,36,'강렬한,위스키'],
    ['AMERICAN','포로지스 싱글배럴','Four Roses Single Barrel',17,31,'달콤한,과일향,위스키'],
    ['AMERICAN','휘슬피그 10Y','Whistlepig 10Y',25,45,'강렬한,위스키'],
    ['AMERICAN','노아스밀',"Noah's Mill",35,63,'달콤한,강렬한,위스키'],
    ['AMERICAN','올드 에즈라 7Y 배럴 스트렝스 버번','Old Ezra 7Y Barrel Strength Bourbon',35,63,'달콤한,강렬한,위스키'],
    ['AMERICAN','올드 에즈라 7Y 배럴 스트렝스 라이','Old Ezra 7Y Barrel Strength Rye',33,59,'강렬한,위스키'],
    ['AMERICAN','부커스 Batch 2026 01E',"Booker's Batch 2026 01E",40,72,'달콤한,강렬한,위스키'],
    ['AMERICAN','1792 스몰 배치','1792 Small Batch',18,32,'달콤한,위스키'],
    ['AMERICAN','1792 풀 푸르프','1792 Full Proof',28,50,'달콤한,강렬한,위스키'],
    ['AMERICAN','엔젤스 엔비',"Angel's Envy",17,31,'달콤한,과일향,위스키'],
    ['AMERICAN','이글레어','Eglair',25,45,'달콤한,위스키'],
    ['AMERICAN','웰러 12Y','Weller 12Y',36,65,'달콤한,부드러운,위스키'],
    ['AMERICAN','E.H 테일러','E.H. Taylor',40,73,'달콤한,강렬한,위스키'],
    ['CAMPBELTOWN','글렌스코시아 10Y','GlenScotia 10Y',20,36,'달콤한,스모키,위스키,입문자'],
    ['CAMPBELTOWN','글렌스코시아 15Y','GlenScotia 15Y',33,'','달콤한,스모키,위스키'],
    ['CAMPBELTOWN','글렌스코시아 빅토리아나','GlenScotia Victoriana',37,67,'달콤한,강렬한,위스키'],
    ['CAMPBELTOWN','글렌스코시아 21Y','Glen Scotia 21Y',150,'','달콤한,강렬한,위스키'],
    ['CAMPBELTOWN','캠벨타운 로크','Campbeltown Loch',25,'','달콤한,위스키'],
    ['CAMPBELTOWN','킬커란 12Y','Kilkerran 12Y',40,'','달콤한,스모키,위스키'],
    ['CAMPBELTOWN','킬커란 16Y','Kilkerran 16Y',50,'','달콤한,강렬한,위스키'],
    ['CAMPBELTOWN','킬커란 CS','Kilkerran CS',45,'','강렬한,스모키,위스키'],
    ['CAMPBELTOWN','스프링뱅크 10Y','Springbank 10Y',40,'','달콤한,스모키,위스키'],
    ['CAMPBELTOWN','스프링뱅크 100 프루프 5Y','Springbank 100 Proof 5Y',35,'','스모키,강렬한,위스키'],
    ['CAMPBELTOWN','스프링뱅크 12Y CS','Springbank 12Y CS',60,'','스모키,강렬한,위스키'],
    ['CAMPBELTOWN','롱로우 피티드','Longrow Peated',40,'','스모키,강렬한,위스키'],
    ['OTHER','카바란 올로로소 셰리 오크','Kavalan Oloroso Sherry Oak',40,72,'달콤한,강렬한,위스키'],
    ['OTHER','카바란 솔리스트 올로로소 셰리 캐스크','Kavalan Solist Oloroso Sherry Cask',45,81,'달콤한,강렬한,위스키'],
    ['OTHER','카바란 솔리스트 비노바리끄','Kavalan Solist Vinho Barrique',45,81,'달콤한,강렬한,위스키'],
    ['OTHER','알프레드 지로 헤리티지','Alfred Giraud Heritage',33,59,'달콤한,과일향,위스키'],
    ['OTHER','알프레드 지로 하모니','Alfred Giraud Harmonic',38,68,'달콤한,위스키'],
    ['OTHER','암룻 퓨전','Amrut Fusion',23,41,'달콤한,스모키,위스키'],
    ['OTHER','암룻 인디언','Amrut Indian',27,49,'달콤한,위스키'],
    ['OTHER','암룻 피티드 인디언 CS','Amrut Peated Indian CS',27,49,'스모키,강렬한,위스키'],
    ['OTHER','폴존 PX','Paul John PX',25,45,'달콤한,과일향,위스키'],
    ['OTHER','폴존 올로로소','Paul John Oloroso',28,50,'달콤한,위스키'],
    ['BLENDED','몽키숄더','Monkey Shoulder',12,22,'달콤한,부드러운,위스키,입문자'],
    ['BLENDED','조니워커 더블블랙','Johnnie Walker Double Black',15,27,'달콤한,스모키,위스키,입문자'],
    ['BLENDED','조니워커 블루라벨','Johnnie Walker Blue Label',50,90,'달콤한,부드러운,강렬한,위스키'],
    ['BLENDED','로얄 살루트 21Y','Royal Salute 21Y',38,69,'달콤한,부드러운,위스키'],
    ['BLENDED','혜도니즘','Compass Box Hedonism',48,'','달콤한,부드러운,위스키'],
    ['BLENDED','브륄레 로얄','Compass Box Brûlée Royale',55,'','달콤한,위스키'],
    ['JAPANESE','닛카 요이치','Nikka Yoichi',22,40,'스모키,강렬한,위스키'],
    ['JAPANESE','닛카 미야기쿄','Nikka Miyagikyo',22,40,'달콤한,과일향,부드러운,위스키'],
    ['JAPANESE','하쿠슈 12 100주년','Hakushu 12 100th Anniversary',45,'','스모키,과일향,위스키'],
    ['JAPANESE','히비키 하모니','Hibiki Harmony',30,54,'달콤한,과일향,부드러운,위스키,입문자'],
    ['JAPANESE','히비키 하모니 마스터 셀렉','Hibiki Harmony Master Select',45,81,'달콤한,부드러운,위스키'],
    ['JAPANESE','야마자키 12Y','Yamazaki 12Y',40,72,'달콤한,과일향,부드러운,위스키'],
    ['JAPANESE','아케시 소한','Akkeshi Sokan',55,99,'스모키,강렬한,위스키'],
    ['JAPANESE','이치로스 몰트 앤 그레인',"Ichiro's Malt & Grain",36,65,'달콤한,과일향,위스키'],
    ['SPECIAL & IB','제기 (JEGI – Craftbros × Highcost)','JEGI',30,54,'달콤한,위스키'],
    ['SPECIAL & IB','글렌 알라키 17Y','GlenAllachie 17Y',45,'','달콤한,강렬한,위스키'],
    ['SPECIAL & IB','스페이사이드(M) 14년 #16 스몰 배치','Speyside 2010 14Y #16 Small Batch',35,63,'달콤한,위스키'],
    ['SPECIAL & IB','부나하벤 스토이사 11Y 이비스코 디켄터','Bunnahabhain Staoisha 2013 11Y Ibisco Decante',33,59,'스모키,달콤한,위스키'],
    ['SPECIAL & IB','트랜스컨티넨탈 럼라인 니카라과','Transcontinental RumLine Nicaragua',35,63,'달콤한,과일향,위스키'],
    ['SPECIAL & IB','보리밭을 흔드는 바람','Barley Field Wind',40,72,'달콤한,위스키'],
  ]);

  setupSheet(ss, 'FOOD', [
    ['섹션','한국어','영어','가격','설명'],
    ['First Pair — 첫 잔과 함께','토마토 모짜','Olive, Tomato & Mozzarella',18,'산뜻하고 깔끔한 맛으로 첫 잔이나 가벼운 스페이사이드 위스키와 추천드립니다.'],
    ['First Pair — 첫 잔과 함께','브리치즈 구이','Baked Brie Cheese',25,'셰리 캐스크의 달콤하고 풍부한 위스키와 훌륭한 조화를 이룹니다.'],
    ['Perfect Pair — 잔이 비워질 즈음','치즈 & 샤퀴테리 플래터','Cheese & Charcuterie Platter',35,'위스키의 풍미를 잘 살려주는 가장 클래식한 페어링입니다.'],
    ['Perfect Pair — 잔이 비워질 즈음','소세지 플래터','Sausage Platter',20,'훈연향과 육즙이 버번이나 가벼운 하이볼과 잘 어울립니다.'],
    ['Perfect Pair — 잔이 비워질 즈음','똠얌 신라면','Ramen (Thai style)',8,'익숙한 신라면에 태국의 향을 더해 깊은 풍미의 스파이시 누들로, 깔끔한 하이볼이나 맥주와 드셔보세요.'],
    ['Sweet Finish — 마지막 한 잔','츄러스 엔 딥','Churros & Dip (6ea)',15,'버번과 디저트 스타일 위스키의 바닐라 향을 더욱 돋보이게 합니다.'],
    ['Sweet Finish — 마지막 한 잔','헤이즐넛 크럼블 아이스크림','Hazelnut Crumble Ice Cream',13,'피트의 스모키함이나 셰리의 달콤함과 즐기기 좋은 마무리 디저트입니다.'],
  ]);

  setupSheet(ss, 'TASTING', [
    ['번호','이름','가격','구성','설명'],
    ['NO. 1','Indian',45,'Amrut Fusion / Paul John PX / Paul John Oloroso','인도 위스키 세 가지로, 스코틀랜드 밖에도 위스키가 있다는 것을 확인하는 코스입니다.'],
    ['NO. 2','Peat',38,'Ardbeg An Oa / Kilchoman Sanaig / Laphroaig Select','스모키가 무엇인지 궁금하셨던 분을 위한, 아일라 피트 입문 코스입니다.'],
    ['NO. 3','The Peat Monster',99,'Ardbeg Traigh Bhan 19Y / LAGG Batch / Octomore 15.3','피트의 끝까지 가보고 싶은 분을 위한 코스입니다. 옥토모어를 포함합니다.'],
    ['NO. 4','Sweet',50,'GlenAllachie 12Y Moscatel / Glenmorangie Quinta Ruban / Arran Port Cask','각기 다른 와인 캐스크가 만들어내는 단맛의 결을 비교하는 코스입니다.'],
    ['NO. 5','Campbeltown',69,'Springbank 100 Proof 5Y / Longrow Peated / Kilkerran 12Y','캠벨타운 세 증류소를 나란히 비교하는, 국내에서도 흔치 않은 코스입니다.'],
    ['NO. 6','Asia',52,'JEGI / Kavalan Oloroso Sherry Oak / Nikka Miyagikyo','한국·대만·일본. 아시아 위스키의 차이를 확인하는 코스입니다.'],
    ['No. 7','Port',57,'Kranemann Tawny 10 / 20 / 30','오래된 목재 캐스크에서 숙성하여, 숙성 연수에 따른 풍미와 복합미의 차이를 느낄 수 있습니다.'],
  ]);

  setupSheet(ss, 'BOTTLE', [
    ['한국어','영어','가격'],
    ['글렌리벳 12년','The Glenlivet 12Y',300],
    ['글렌리벳 15년','The Glenlivet 15Y',450],
    ['글렌피딕 12년','Glenfiddich 12Y',330],
    ['글렌피딕 15년','Glenfiddich 15Y',460],
    ['글렌모렌지 오리지널','Glenmorangie Original',300],
    ['글렌모렌지 라산타','Glenmorangie Lasanta',470],
    ['발베니 12년','The Balvenie 12Y',360],
    ['발베니 14년','The Balvenie 14Y',550],
    ['달모어 12년','The Dalmore 12Y',390],
    ['달모어 12년 셰리','The Dalmore 12Y Sherry Cask',520],
    ['달모어 15년','The Dalmore 15Y',650],
    ['글렌알라키 12년','GlenAllachie 12Y',420],
    ['조니워커 블루','Johnnie Walker Blue Label',820],
    ['이글레어 10년','Eagle Rare 10Y',460],
    ['버팔로 트레이스','Buffalo Trace',240],
  ]);

  setupSheet(ss, 'OTHER', [
    ['카테고리','한국어','영어','30ml가격','60ml가격','가격','설명'],
    ['COGNAC','헤네시 XO','Hennessy XO',60,109,'',''],
    ['COGNAC','헤네시 VSOP','Hennessy VSOP',25,45,'',''],
    ['COGNAC','마르텔 VSOP','Martell VSOP',18,32,'',''],
    ['COGNAC','까뮤 보더리 XO','Camus Borderies XO',55,99,'',''],
    ['PORT WINE','크레인만 타우니 10년','Kranemann Tawny 10Y',15,27,'',''],
    ['PORT WINE','크레인만 타우니 20년','Kranemann Tawny 20Y',25,45,'',''],
    ['PORT WINE','크레인만 타우니 30년','Kranemann Tawny 30Y',55,99,'',''],
    ['GIN','탱커레이','Tanqueray',13,23,'',''],
    ['GIN','헨드릭스 진',"Hendrick's Gin",20,36,'',''],
    ['GIN','몽키47','Monkey 47',20,36,'',''],
    ['GIN','크리스찬 드루앵 르 진','Christian Drouin Le Gin',25,45,'',''],
    ['GIN','더 보타니스트','The Botanist',18,32,'',''],
    ['GIN','포필리스 진 크리스마스 에디션','Populis Gin Christmas Edition',24,43,'',''],
    ['TEQUILA','신코로 레포사도','Cincoro Reposado',35,63,'',''],
    ['TEQUILA','신코로 아네호','Cincoro Añejo',40,72,'',''],
    ['RUM','에미넨테 럼','Eminente Reserva Rum',23,41,'',''],
    ['RUM','니카라과 럼','Nicaraguan Rum',35,63,'',''],
    ['RUM','디플로마티코','Diplomatico',18,32,'',''],
    ['RUM','골드 오브 모리서스','Gold of Mauritius Black 48',18,32,'',''],
    ['BEER','포쉐트','Fourchette','','',18,'미슐랭 스타 셰프와 벨기에 반스틴베르그 양조장이 협업한 트리펠 스타일 맥주. 시트러스·꽃향과 부드러운 단맛. 330ml · 7.5%'],
    ['CALVADOS','크리스찬 드루앵 르 진','Christian Drouin Le Gin',25,45,'',''],
    ['CALVADOS','크리스찬 드루앵 XO','Christian Drouin XO',28,50,'',''],
    ['CALVADOS','크리스찬 드루앵 뽐 프리지니에르',"Calvados Pays d'Auge Pomme Prisonnière",40,72,'',''],
    ['CALVADOS','크리스찬 드루앵 × 치치부 엔젤스','Christian Drouin × Chichibu Angels Experimental #11',45,81,'',''],
    ['CALVADOS','드루앵 밀레지메 2003','Les Millésimes de Christian Drouin 2003',45,81,'',''],
    ['CALVADOS','드루앵 밀레지메 2004','Les Millésimes de Christian Drouin 2004',50,90,'',''],
    ['CALVADOS','드루앵 밀레지메 2005','Les Millésimes de Christian Drouin 2005',47,85,'',''],
    ['CIDRE','크리스찬 드루앵 시드르 브뤼','Christian Drouin Cidre Brut','','',60,'사과를 착즙 후 겨울 동안 자연 발효시켜 탄산가스를 주입한 노르망디 지역의 전통 발효주. 750ml · Alc. 4.5%'],
    ['CIDRE','크리스찬 드루앵 뽀아레','Christian Drouin Poiré','','',80,'배 주스를 발효하는 과정에서 자연스러운 기포가 생기는 노르망디 지역의 배 발효주. 750ml · Alc. 4.0%'],
  ]);

  SpreadsheetApp.getUi().alert('✓ 모든 메뉴 데이터가 시트에 입력되었습니다!');
}

// ─── 헬퍼: 시트 생성 및 데이터 입력 ──────────────────────────────────────────
function setupSheet(ss, name, data) {
  let sheet = ss.getSheetByName(name);
  if (!sheet) {
    sheet = ss.insertSheet(name);
  } else {
    sheet.clearContents();
  }
  sheet.getRange(1, 1, data.length, data[0].length).setValues(data);

  // 헤더 행 스타일
  const header = sheet.getRange(1, 1, 1, data[0].length);
  header.setBackground('#1a1a1a').setFontColor('#ffffff').setFontWeight('bold');
  sheet.setFrozenRows(1);
}
